print ('Введите число a=')
a = float(input())
print ('Введите число b=')
b = float(input())
print('Выберите операцию')
print('1 - Сложить a + b')
print('2 - Вычесть a - b')
print('3 - Умножить a * b')
print('4 - Разделить a / b')
c = int(input())
